apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-web-view.fullname" . }}-config
  labels: {{ include "kube-web-view.labels" . | nindent 4 }}
  {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | indent 4 }}
  {{- end }}
data:
{{ toYaml .Values.config.main | indent 2 }}
