---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-web-view.fullname" . }}
  labels:
{{ include "kube-web-view.labels" . | indent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-web-view.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.hooks }}
      annotations:
        checksum/hooks: {{ include (print $.Template.BasePath "/hooks-py-cm.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "kube-web-view.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "kube-web-view.fullname" . }}
      {{- if .Values.hooks }}
      volumes:
        - name: {{ template "kube-web-view.fullname" . }}-hooks-py
          configMap:
            name: {{ template "kube-web-view.fullname" . }}-hooks-py
      {{- end }}
      containers:
      - name: {{ template "kube-web-view.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - --port={{ .Values.service.internalPort }}
        {{- if .Values.args }}
        {{- range .Values.args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ template "kube-web-view.fullname" . }}-config
          - secretRef:
              name: {{ template "kube-web-view.fullname" . }}-config
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        {{- if .Values.hooks }}
        volumeMounts:
          - name: "{{ template "kube-web-view.fullname" . }}-hooks-py"
            mountPath: /hooks.py
            subPath: hooks.py
            readOnly: true
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
        resources: {{ toYaml .Values.resources | nindent 12 }}
