---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "kube-web-view.labels" . | indent 4 }}
  name:  {{ include "kube-web-view.fullname" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ include "kube-web-view.labels" . | indent 4 }}
  name:  {{ include "kube-web-view.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: [list, get]
- nonResourceURLs:
  - '*'
  verbs: [list, get]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
{{ include "kube-web-view.labels" . | indent 4 }}
  name:  {{ include "kube-web-view.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-web-view.fullname" . }}
subjects:
- kind: ServiceAccount
  name: kube-web-view
  name: {{ include "kube-web-view.fullname" . }}
  namespace: {{ .Release.Namespace }}
