---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-web-view.fullname" . }}
  labels:
{{ include "kube-web-view.labels" . | indent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "kube-web-view.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
