---
apiVersion: v2
name: kube-better-node
description: Small tool for finding a better node, based on preferredDuringSchedulingIgnoredDuringExecution
version: 0.0.5
appVersion: 0.0.2
maintainers:
  - email: r.komkov@gmail.com
    name: decayofmind
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
keywords:
  - utility
  - cron
  - scheduler
